[package]
name = "sel4-entry"
version = "0.0.1"
publish = false
build = "build.rs"

[lib]
name = "sel4_entry"
path = "src/lib.rs"

[dependencies]
libsel4-sys = {path = "../libsel4-sys"}

[build-dependencies]
maplit = "0.1.3"
